"""
Weekly Financial Summary Template
Generates standardized CEO reports for weekly financial performance
"""
import json
from datetime import datetime, timedelta
from typing import Dict, List
import logging

# Set up logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

def generate_weekly_summary_report(ledger_summary: Dict) -> str:
    """
    Generate a formatted weekly financial summary report for CEO.

    Args:
        ledger_summary: Summary data from LedgerManager.generate_weekly_summary()

    Returns:
        Formatted string report
    """
    report_date = datetime.now().strftime("%B %d, %Y")
    week_start = datetime.strptime(ledger_summary['week_start'], "%Y-%m-%d").strftime("%B %d")
    week_end = datetime.strptime(ledger_summary['week_end'], "%Y-%m-%d").strftime("%B %d")

    # Format the report
    report = f"""
WEEKLY FINANCIAL SUMMARY REPORT
===============================
Report Date: {report_date}
Reporting Period: {week_start} - {week_end}
Currency: {ledger_summary['currency']}
Generated by: AI Financial Assistant

INCOME & EXPENSES SUMMARY
-------------------------
Total Income: ${ledger_summary['total_income']:,.2f}
Total Expenses: ${ledger_summary['total_expenses']:,.2f}
Net Profit/Loss: ${ledger_summary['profit_loss']:,.2f}

"""

    # Income breakdown
    if ledger_summary['income_by_category']:
        report += "INCOME BREAKDOWN BY CATEGORY\n"
        report += "---------------------------\n"
        for category, amount in sorted(ledger_summary['income_by_category'].items(), key=lambda x: x[1], reverse=True):
            report += f"  {category.title()}: ${amount:,.2f}\n"
        report += "\n"

    # Expense breakdown
    if ledger_summary['expenses_by_category']:
        report += "EXPENSE BREAKDOWN BY CATEGORY\n"
        report += "----------------------------\n"
        for category, amount in sorted(ledger_summary['expenses_by_category'].items(), key=lambda x: x[1], reverse=True):
            report += f"  {category.title()}: ${amount:,.2f}\n"
        report += "\n"

    # Trend analysis
    if 'trend_analysis' in ledger_summary and ledger_summary['trend_analysis']:
        trend = ledger_summary['trend_analysis']

        report += "TREND ANALYSIS\n"
        report += "--------------\n"

        # Top income sources
        if trend['top_income_sources']:
            report += "Top Income Sources:\n"
            for source, amount in trend['top_income_sources'][:3]:  # Top 3
                report += f"  {source.title()}: ${amount:,.2f}\n"

        # Top expense categories
        if trend['top_expense_categories']:
            report += "Top Expense Categories:\n"
            for category, amount in trend['top_expense_categories'][:3]:  # Top 3
                report += f"  {category.title()}: ${amount:,.2f}\n"

        report += "\n"

    # Week-over-week comparison
    if 'comparisons' in ledger_summary and ledger_summary['comparisons']:
        comparison = ledger_summary['comparisons']

        report += "WEEK-OVER-WEEK COMPARISON\n"
        report += "-------------------------\n"
        report += f"Income Change: ${comparison['income_change_from_prev_week']:,.2f}\n"
        report += f"Expense Change: ${comparison['expense_change_from_prev_week']:,.2f}\n"
        report += f"Profit/Loss Change: ${comparison['profit_loss_change_from_prev_week']:,.2f}\n"

    # Key metrics
    report += "\n"
    report += "KEY METRICS\n"
    report += "-----------\n"
    if ledger_summary['total_income'] > 0:
        profit_margin = (ledger_summary['profit_loss'] / ledger_summary['total_income']) * 100
        report += f"Profit Margin: {profit_margin:.2f}%\n"

    # Recommendations based on data
    report += "\n"
    report += "AI RECOMMENDATIONS\n"
    report += "------------------\n"

    if comparison.get('profit_loss_change_from_prev_week', 0) < 0:
        report += "- Profit decreased compared to last week. Consider reviewing expenses.\n"
    elif comparison.get('profit_loss_change_from_prev_week', 0) > 0:
        report += "- Profit increased compared to last week. Maintain current strategies.\n"

    if ledger_summary['expenses_by_category'].get('marketing', 0) / ledger_summary.get('total_income', 1) > 0.15:
        report += "- Marketing expenses exceed 15% of income. Consider optimizing ad spend.\n"

    if not ledger_summary['income_by_category'].get('sales'):
        report += "- No sales income recorded. Focus on revenue-generating activities.\n"

    report += "\n"
    report += "REPORT GENERATED: This report was automatically generated by the AI Financial Assistant.\n"

    return report

def save_weekly_summary_report(ledger_summary: Dict, filename: str = None) -> str:
    """
    Save the weekly summary report to a file.

    Args:
        ledger_summary: Summary data from LedgerManager.generate_weekly_summary()
        filename: Optional filename (will be generated if not provided)

    Returns:
        Path to saved file
    """
    if not filename:
        week_start = ledger_summary['week_start']
        filename = f"weekly_financial_summary_{week_start}.txt"

    # Create reports directory if it doesn't exist
    import os
    reports_dir = os.path.join("Reports", "Financial")
    os.makedirs(reports_dir, exist_ok=True)

    filepath = os.path.join(reports_dir, filename)

    report = generate_weekly_summary_report(ledger_summary)

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(report)

    logger.info(f"Weekly summary report saved to {filepath}")
    return filepath

def generate_detailed_weekly_summary(ledger_summary: Dict) -> Dict:
    """
    Generate a more detailed JSON version of the weekly summary.

    Args:
        ledger_summary: Summary data from LedgerManager.generate_weekly_summary()

    Returns:
        Dictionary with detailed summary data
    """
    week_start = datetime.strptime(ledger_summary['week_start'], "%Y-%m-%d").strftime("%B %d, %Y")
    week_end = datetime.strptime(ledger_summary['week_end'], "%Y-%m-%d").strftime("%B %d, %Y")

    detailed_summary = {
        "metadata": {
            "report_date": datetime.now().isoformat(),
            "reporting_period": {
                "start": ledger_summary['week_start'],
                "end": ledger_summary['week_end'],
                "formatted_start": week_start,
                "formatted_end": week_end
            },
            "currency": ledger_summary['currency'],
            "generated_by": "AI Financial Assistant"
        },
        "financial_highlights": {
            "total_income": ledger_summary['total_income'],
            "total_expenses": ledger_summary['total_expenses'],
            "net_profit_loss": ledger_summary['profit_loss'],
            "profit_margin_percent": (
                (ledger_summary['profit_loss'] / ledger_summary['total_income']) * 100
                if ledger_summary['total_income'] > 0 else 0
            )
        },
        "income_breakdown": {
            "by_category": ledger_summary['income_by_category'],
            "count": len(ledger_summary['income_by_category'])
        },
        "expense_breakdown": {
            "by_category": ledger_summary['expenses_by_category'],
            "count": len(ledger_summary['expenses_by_category'])
        },
        "trend_analysis": {
            "week_over_week_comparison": ledger_summary.get('comparisons', {}),
            "top_income_sources": ledger_summary.get('trend_analysis', {}).get('top_income_sources', []),
            "top_expense_categories": ledger_summary.get('trend_analysis', {}).get('top_expense_categories', [])
        },
        "key_recommendations": []
    }

    # Add AI-generated recommendations
    recommendations = []

    comparison = ledger_summary.get('comparisons', {})
    if comparison.get('profit_loss_change_from_prev_week', 0) < 0:
        recommendations.append({
            "type": "profitability",
            "priority": "high",
            "message": "Profit decreased compared to last week. Consider reviewing expenses and revenue strategies."
        })
    elif comparison.get('profit_loss_change_from_prev_week', 0) > 0:
        recommendations.append({
            "type": "profitability",
            "priority": "low",
            "message": "Profit increased compared to last week. Maintain current successful strategies."
        })

    # Check marketing spend ratio
    total_income = ledger_summary['total_income']
    marketing_expense = ledger_summary['expenses_by_category'].get('marketing', 0)
    if total_income > 0 and (marketing_expense / total_income) > 0.15:
        recommendations.append({
            "type": "expense_optimization",
            "priority": "medium",
            "message": "Marketing expenses exceed 15% of income. Consider optimizing ad spend efficiency."
        })

    # Check sales income
    if not ledger_summary['income_by_category'].get('sales'):
        recommendations.append({
            "type": "revenue",
            "priority": "high",
            "message": "No sales income recorded this week. Focus on revenue-generating activities."
        })

    detailed_summary["key_recommendations"] = recommendations

    return detailed_summary

# Example usage
if __name__ == "__main__":
    # Example of how this would be used (with mock data since we don't have an active ledger manager)
    mock_summary_data = {
        'week_start': '2026-02-15',
        'week_end': '2026-02-21',
        'total_income': 5420.50,
        'total_expenses': 2150.00,
        'profit_loss': 3270.50,
        'currency': 'USD',
        'income_by_category': {
            'sales': 4000.00,
            'consulting': 1420.50
        },
        'expenses_by_category': {
            'marketing': 800.00,
            'salaries': 1000.00,
            'utilities': 350.00
        },
        'comparisons': {
            'income_change_from_prev_week': 220.50,
            'expense_change_from_prev_week': -50.00,
            'profit_loss_change_from_prev_week': 270.50
        },
        'trend_analysis': {
            'top_income_sources': [
                ['sales', 4000.00],
                ['consulting', 1420.50]
            ],
            'top_expense_categories': [
                ['salaries', 1000.00],
                ['marketing', 800.00],
                ['utilities', 350.00]
            ]
        }
    }

    print("Example Weekly Financial Summary Report:")
    print("=" * 50)

    report = generate_weekly_summary_report(mock_summary_data)
    print(report)

    # Also generate detailed version
    detailed = generate_detailed_weekly_summary(mock_summary_data)
    print("\nDetailed Summary (JSON format):")
    print(json.dumps(detailed, indent=2))